version: "3.7"

services:
  prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: frontend-repository-extenciones  # Cambia el nombre de la imagen
    container_name: extenciones-docker-nextjs-1
    ports:
      - "3002:3000"
    env_file:
      - .env

volumes:
  node_modules: