version: "3.7"

services:
  prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: frontend-repository-procesos  # Cambia el nombre de la imagen
    container_name: procesos-docker-nextjs-1
    ports:
      - "3003:3000"
    env_file:
      - .env
    networks:
      - my_new_network  # Asegúrate de añadir la red aquí

networks:
  my_new_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16  # Cambia a una subred no usada
