version: "3.7"

services:
  prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: frontend-repository-procesos  # Cambia el nombre de la imagen
    container_name: procesos-docker-nextjs-1
    ports:
      - "3003:3000"
    env_file:
      - .env

volumes:
  node_modules: