version: "3.7"

services:
  prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: frontend-repository-procesos
    container_name: procesos-docker-nextjs-1
    ports:
      - "3003:3000"
    env_file:
      - .env
    networks:
      - my_new_network  # Asocia el servicio con la red

networks:
  my_new_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/24 # Asegúrate de usar una subred no en uso
