version: "3.7"

services:
  prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: frontend-repository-procesos
    container_name: procesos-docker-nextjs-1
    ports:
      - "3003:3000"
    env_file:
      - .env
    networks:
      my_new_network:
        ipv4_address: 192.168.240.10  # Puedes elegir una dirección específica si es necesario

networks:
  my_new_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.240.0/20  # Ajusta la subred aquí
